//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "FK_CoderId", "Coders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TopCoder.Analysis.Data.Coder), "RoundResults", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TopCoder.Analysis.Data.RoundResult), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_RoundId", "Rounds", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TopCoder.Analysis.Data.Round), "RoundResults", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TopCoder.Analysis.Data.RoundResult), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_FirstRoundId", "Round", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TopCoder.Analysis.Data.Round), "Coder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TopCoder.Analysis.Data.Coder), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_LastRoundId", "Round", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TopCoder.Analysis.Data.Round), "Coder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TopCoder.Analysis.Data.Coder), true)]

#endregion

namespace TopCoder.Analysis.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TcAnalysisDataModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TcAnalysisDataModel object using the connection string found in the 'TcAnalysisDataModel' section of the application configuration file.
        /// </summary>
        public TcAnalysisDataModel() : base("name=TcAnalysisDataModel", "TcAnalysisDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TcAnalysisDataModel object.
        /// </summary>
        public TcAnalysisDataModel(string connectionString) : base(connectionString, "TcAnalysisDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TcAnalysisDataModel object.
        /// </summary>
        public TcAnalysisDataModel(EntityConnection connection) : base(connection, "TcAnalysisDataModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Coder> Coders
        {
            get
            {
                if ((_Coders == null))
                {
                    _Coders = base.CreateObjectSet<Coder>("Coders");
                }
                return _Coders;
            }
        }
        private ObjectSet<Coder> _Coders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoundResult> RoundResults
        {
            get
            {
                if ((_RoundResults == null))
                {
                    _RoundResults = base.CreateObjectSet<RoundResult>("RoundResults");
                }
                return _RoundResults;
            }
        }
        private ObjectSet<RoundResult> _RoundResults;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Round> Rounds
        {
            get
            {
                if ((_Rounds == null))
                {
                    _Rounds = base.CreateObjectSet<Round>("Rounds");
                }
                return _Rounds;
            }
        }
        private ObjectSet<Round> _Rounds;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Coders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCoders(Coder coder)
        {
            base.AddObject("Coders", coder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoundResults EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoundResults(RoundResult roundResult)
        {
            base.AddObject("RoundResults", roundResult);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rounds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRounds(Round round)
        {
            base.AddObject("Rounds", round);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Coder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Coder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Coder object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="firstRoundId">Initial value of the FirstRoundId property.</param>
        /// <param name="lastRoundId">Initial value of the LastRoundId property.</param>
        /// <param name="roundsCount">Initial value of the RoundsCount property.</param>
        /// <param name="tc_Rating">Initial value of the Tc_Rating property.</param>
        /// <param name="tc_Volatility">Initial value of the Tc_Volatility property.</param>
        /// <param name="elo_Rating">Initial value of the Elo_Rating property.</param>
        /// <param name="elo_KFactor">Initial value of the Elo_KFactor property.</param>
        public static Coder CreateCoder(global::System.Int32 id, global::System.String handle, global::System.Int32 firstRoundId, global::System.Int32 lastRoundId, global::System.Int32 roundsCount, global::System.Int32 tc_Rating, global::System.Int32 tc_Volatility, global::System.Int32 elo_Rating, global::System.Int32 elo_KFactor)
        {
            Coder coder = new Coder();
            coder.Id = id;
            coder.Handle = handle;
            coder.FirstRoundId = firstRoundId;
            coder.LastRoundId = lastRoundId;
            coder.RoundsCount = roundsCount;
            coder.Tc_Rating = tc_Rating;
            coder.Tc_Volatility = tc_Volatility;
            coder.Elo_Rating = elo_Rating;
            coder.Elo_KFactor = elo_KFactor;
            return coder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                OnHandleChanging(value);
                ReportPropertyChanging("Handle");
                _Handle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Handle");
                OnHandleChanged();
            }
        }
        private global::System.String _Handle;
        partial void OnHandleChanging(global::System.String value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FirstRoundId
        {
            get
            {
                return _FirstRoundId;
            }
            set
            {
                OnFirstRoundIdChanging(value);
                ReportPropertyChanging("FirstRoundId");
                _FirstRoundId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstRoundId");
                OnFirstRoundIdChanged();
            }
        }
        private global::System.Int32 _FirstRoundId;
        partial void OnFirstRoundIdChanging(global::System.Int32 value);
        partial void OnFirstRoundIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LastRoundId
        {
            get
            {
                return _LastRoundId;
            }
            set
            {
                OnLastRoundIdChanging(value);
                ReportPropertyChanging("LastRoundId");
                _LastRoundId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastRoundId");
                OnLastRoundIdChanged();
            }
        }
        private global::System.Int32 _LastRoundId;
        partial void OnLastRoundIdChanging(global::System.Int32 value);
        partial void OnLastRoundIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoundsCount
        {
            get
            {
                return _RoundsCount;
            }
            set
            {
                OnRoundsCountChanging(value);
                ReportPropertyChanging("RoundsCount");
                _RoundsCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoundsCount");
                OnRoundsCountChanged();
            }
        }
        private global::System.Int32 _RoundsCount;
        partial void OnRoundsCountChanging(global::System.Int32 value);
        partial void OnRoundsCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_Rating
        {
            get
            {
                return _Tc_Rating;
            }
            set
            {
                OnTc_RatingChanging(value);
                ReportPropertyChanging("Tc_Rating");
                _Tc_Rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_Rating");
                OnTc_RatingChanged();
            }
        }
        private global::System.Int32 _Tc_Rating;
        partial void OnTc_RatingChanging(global::System.Int32 value);
        partial void OnTc_RatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_Volatility
        {
            get
            {
                return _Tc_Volatility;
            }
            set
            {
                OnTc_VolatilityChanging(value);
                ReportPropertyChanging("Tc_Volatility");
                _Tc_Volatility = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_Volatility");
                OnTc_VolatilityChanged();
            }
        }
        private global::System.Int32 _Tc_Volatility;
        partial void OnTc_VolatilityChanging(global::System.Int32 value);
        partial void OnTc_VolatilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Elo_Rating
        {
            get
            {
                return _Elo_Rating;
            }
            set
            {
                OnElo_RatingChanging(value);
                ReportPropertyChanging("Elo_Rating");
                _Elo_Rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elo_Rating");
                OnElo_RatingChanged();
            }
        }
        private global::System.Int32 _Elo_Rating;
        partial void OnElo_RatingChanging(global::System.Int32 value);
        partial void OnElo_RatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Elo_KFactor
        {
            get
            {
                return _Elo_KFactor;
            }
            set
            {
                OnElo_KFactorChanging(value);
                ReportPropertyChanging("Elo_KFactor");
                _Elo_KFactor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elo_KFactor");
                OnElo_KFactorChanged();
            }
        }
        private global::System.Int32 _Elo_KFactor;
        partial void OnElo_KFactorChanging(global::System.Int32 value);
        partial void OnElo_KFactorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CoderId", "RoundResults")]
        public EntityCollection<RoundResult> RoundResults
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoundResult>("Model.FK_CoderId", "RoundResults");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoundResult>("Model.FK_CoderId", "RoundResults", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_FirstRoundId", "Round")]
        public Round FirstRound
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_FirstRoundId", "Round").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_FirstRoundId", "Round").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Round> FirstRoundReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_FirstRoundId", "Round");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Round>("Model.FK_FirstRoundId", "Round", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_LastRoundId", "Round")]
        public Round LastRound
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_LastRoundId", "Round").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_LastRoundId", "Round").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Round> LastRoundReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_LastRoundId", "Round");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Round>("Model.FK_LastRoundId", "Round", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Round")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Round : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Round object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="totalCodersCount">Initial value of the TotalCodersCount property.</param>
        /// <param name="divOneCodersCount">Initial value of the DivOneCodersCount property.</param>
        /// <param name="divTwoCodersCount">Initial value of the DivTwoCodersCount property.</param>
        /// <param name="competitionFactor">Initial value of the CompetitionFactor property.</param>
        public static Round CreateRound(global::System.Int32 id, global::System.String name, global::System.DateTime date, global::System.Int32 totalCodersCount, global::System.Int32 divOneCodersCount, global::System.Int32 divTwoCodersCount, global::System.Double competitionFactor)
        {
            Round round = new Round();
            round.Id = id;
            round.Name = name;
            round.Date = date;
            round.TotalCodersCount = totalCodersCount;
            round.DivOneCodersCount = divOneCodersCount;
            round.DivTwoCodersCount = divTwoCodersCount;
            round.CompetitionFactor = competitionFactor;
            return round;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalCodersCount
        {
            get
            {
                return _TotalCodersCount;
            }
            set
            {
                OnTotalCodersCountChanging(value);
                ReportPropertyChanging("TotalCodersCount");
                _TotalCodersCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalCodersCount");
                OnTotalCodersCountChanged();
            }
        }
        private global::System.Int32 _TotalCodersCount;
        partial void OnTotalCodersCountChanging(global::System.Int32 value);
        partial void OnTotalCodersCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DivOneCodersCount
        {
            get
            {
                return _DivOneCodersCount;
            }
            set
            {
                OnDivOneCodersCountChanging(value);
                ReportPropertyChanging("DivOneCodersCount");
                _DivOneCodersCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DivOneCodersCount");
                OnDivOneCodersCountChanged();
            }
        }
        private global::System.Int32 _DivOneCodersCount;
        partial void OnDivOneCodersCountChanging(global::System.Int32 value);
        partial void OnDivOneCodersCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DivTwoCodersCount
        {
            get
            {
                return _DivTwoCodersCount;
            }
            set
            {
                OnDivTwoCodersCountChanging(value);
                ReportPropertyChanging("DivTwoCodersCount");
                _DivTwoCodersCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DivTwoCodersCount");
                OnDivTwoCodersCountChanged();
            }
        }
        private global::System.Int32 _DivTwoCodersCount;
        partial void OnDivTwoCodersCountChanging(global::System.Int32 value);
        partial void OnDivTwoCodersCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CompetitionFactor
        {
            get
            {
                return _CompetitionFactor;
            }
            set
            {
                OnCompetitionFactorChanging(value);
                ReportPropertyChanging("CompetitionFactor");
                _CompetitionFactor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompetitionFactor");
                OnCompetitionFactorChanged();
            }
        }
        private global::System.Double _CompetitionFactor;
        partial void OnCompetitionFactorChanging(global::System.Double value);
        partial void OnCompetitionFactorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_RoundId", "RoundResults")]
        public EntityCollection<RoundResult> RoundResults
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoundResult>("Model.FK_RoundId", "RoundResults");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoundResult>("Model.FK_RoundId", "RoundResults", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_FirstRoundId", "Coder")]
        public EntityCollection<Coder> FirstRoundCoders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Coder>("Model.FK_FirstRoundId", "Coder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Coder>("Model.FK_FirstRoundId", "Coder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_LastRoundId", "Coder")]
        public EntityCollection<Coder> LastRoundCoders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Coder>("Model.FK_LastRoundId", "Coder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Coder>("Model.FK_LastRoundId", "Coder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="RoundResult")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoundResult : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoundResult object.
        /// </summary>
        /// <param name="roundId">Initial value of the RoundId property.</param>
        /// <param name="coderId">Initial value of the CoderId property.</param>
        /// <param name="division">Initial value of the Division property.</param>
        /// <param name="divisionPlace">Initial value of the DivisionPlace property.</param>
        /// <param name="points">Initial value of the Points property.</param>
        /// <param name="tc_OldRating">Initial value of the Tc_OldRating property.</param>
        /// <param name="tc_NewRating">Initial value of the Tc_NewRating property.</param>
        /// <param name="tc_NewVolatility">Initial value of the Tc_NewVolatility property.</param>
        /// <param name="numberOfRatings">Initial value of the NumberOfRatings property.</param>
        /// <param name="isRated">Initial value of the IsRated property.</param>
        /// <param name="elo_OldRating">Initial value of the Elo_OldRating property.</param>
        /// <param name="elo_NewRating">Initial value of the Elo_NewRating property.</param>
        /// <param name="tc_RatingDiff">Initial value of the Tc_RatingDiff property.</param>
        /// <param name="elo_RatingDiff">Initial value of the Elo_RatingDiff property.</param>
        /// <param name="elo_NewKFactor">Initial value of the Elo_NewKFactor property.</param>
        /// <param name="tc_OldVolatility">Initial value of the Tc_OldVolatility property.</param>
        /// <param name="tc_VolatilityDiff">Initial value of the Tc_VolatilityDiff property.</param>
        public static RoundResult CreateRoundResult(global::System.Int32 roundId, global::System.Int32 coderId, global::System.Int32 division, global::System.Int32 divisionPlace, global::System.Double points, global::System.Int32 tc_OldRating, global::System.Int32 tc_NewRating, global::System.Int32 tc_NewVolatility, global::System.Int32 numberOfRatings, global::System.Boolean isRated, global::System.Int32 elo_OldRating, global::System.Int32 elo_NewRating, global::System.Int32 tc_RatingDiff, global::System.Int32 elo_RatingDiff, global::System.Int32 elo_NewKFactor, global::System.Int32 tc_OldVolatility, global::System.Int32 tc_VolatilityDiff)
        {
            RoundResult roundResult = new RoundResult();
            roundResult.RoundId = roundId;
            roundResult.CoderId = coderId;
            roundResult.Division = division;
            roundResult.DivisionPlace = divisionPlace;
            roundResult.Points = points;
            roundResult.Tc_OldRating = tc_OldRating;
            roundResult.Tc_NewRating = tc_NewRating;
            roundResult.Tc_NewVolatility = tc_NewVolatility;
            roundResult.NumberOfRatings = numberOfRatings;
            roundResult.IsRated = isRated;
            roundResult.Elo_OldRating = elo_OldRating;
            roundResult.Elo_NewRating = elo_NewRating;
            roundResult.Tc_RatingDiff = tc_RatingDiff;
            roundResult.Elo_RatingDiff = elo_RatingDiff;
            roundResult.Elo_NewKFactor = elo_NewKFactor;
            roundResult.Tc_OldVolatility = tc_OldVolatility;
            roundResult.Tc_VolatilityDiff = tc_VolatilityDiff;
            return roundResult;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoundId
        {
            get
            {
                return _RoundId;
            }
            set
            {
                if (_RoundId != value)
                {
                    OnRoundIdChanging(value);
                    ReportPropertyChanging("RoundId");
                    _RoundId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoundId");
                    OnRoundIdChanged();
                }
            }
        }
        private global::System.Int32 _RoundId;
        partial void OnRoundIdChanging(global::System.Int32 value);
        partial void OnRoundIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CoderId
        {
            get
            {
                return _CoderId;
            }
            set
            {
                if (_CoderId != value)
                {
                    OnCoderIdChanging(value);
                    ReportPropertyChanging("CoderId");
                    _CoderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CoderId");
                    OnCoderIdChanged();
                }
            }
        }
        private global::System.Int32 _CoderId;
        partial void OnCoderIdChanging(global::System.Int32 value);
        partial void OnCoderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Division
        {
            get
            {
                return _Division;
            }
            set
            {
                OnDivisionChanging(value);
                ReportPropertyChanging("Division");
                _Division = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Division");
                OnDivisionChanged();
            }
        }
        private global::System.Int32 _Division;
        partial void OnDivisionChanging(global::System.Int32 value);
        partial void OnDivisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DivisionPlace
        {
            get
            {
                return _DivisionPlace;
            }
            set
            {
                OnDivisionPlaceChanging(value);
                ReportPropertyChanging("DivisionPlace");
                _DivisionPlace = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DivisionPlace");
                OnDivisionPlaceChanged();
            }
        }
        private global::System.Int32 _DivisionPlace;
        partial void OnDivisionPlaceChanging(global::System.Int32 value);
        partial void OnDivisionPlaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Points
        {
            get
            {
                return _Points;
            }
            set
            {
                OnPointsChanging(value);
                ReportPropertyChanging("Points");
                _Points = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Points");
                OnPointsChanged();
            }
        }
        private global::System.Double _Points;
        partial void OnPointsChanging(global::System.Double value);
        partial void OnPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_OldRating
        {
            get
            {
                return _Tc_OldRating;
            }
            set
            {
                OnTc_OldRatingChanging(value);
                ReportPropertyChanging("Tc_OldRating");
                _Tc_OldRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_OldRating");
                OnTc_OldRatingChanged();
            }
        }
        private global::System.Int32 _Tc_OldRating;
        partial void OnTc_OldRatingChanging(global::System.Int32 value);
        partial void OnTc_OldRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_NewRating
        {
            get
            {
                return _Tc_NewRating;
            }
            set
            {
                OnTc_NewRatingChanging(value);
                ReportPropertyChanging("Tc_NewRating");
                _Tc_NewRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_NewRating");
                OnTc_NewRatingChanged();
            }
        }
        private global::System.Int32 _Tc_NewRating;
        partial void OnTc_NewRatingChanging(global::System.Int32 value);
        partial void OnTc_NewRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_NewVolatility
        {
            get
            {
                return _Tc_NewVolatility;
            }
            set
            {
                OnTc_NewVolatilityChanging(value);
                ReportPropertyChanging("Tc_NewVolatility");
                _Tc_NewVolatility = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_NewVolatility");
                OnTc_NewVolatilityChanged();
            }
        }
        private global::System.Int32 _Tc_NewVolatility;
        partial void OnTc_NewVolatilityChanging(global::System.Int32 value);
        partial void OnTc_NewVolatilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumberOfRatings
        {
            get
            {
                return _NumberOfRatings;
            }
            set
            {
                OnNumberOfRatingsChanging(value);
                ReportPropertyChanging("NumberOfRatings");
                _NumberOfRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfRatings");
                OnNumberOfRatingsChanged();
            }
        }
        private global::System.Int32 _NumberOfRatings;
        partial void OnNumberOfRatingsChanging(global::System.Int32 value);
        partial void OnNumberOfRatingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRated
        {
            get
            {
                return _IsRated;
            }
            set
            {
                OnIsRatedChanging(value);
                ReportPropertyChanging("IsRated");
                _IsRated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRated");
                OnIsRatedChanged();
            }
        }
        private global::System.Boolean _IsRated;
        partial void OnIsRatedChanging(global::System.Boolean value);
        partial void OnIsRatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Elo_OldRating
        {
            get
            {
                return _Elo_OldRating;
            }
            set
            {
                OnElo_OldRatingChanging(value);
                ReportPropertyChanging("Elo_OldRating");
                _Elo_OldRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elo_OldRating");
                OnElo_OldRatingChanged();
            }
        }
        private global::System.Int32 _Elo_OldRating;
        partial void OnElo_OldRatingChanging(global::System.Int32 value);
        partial void OnElo_OldRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Elo_NewRating
        {
            get
            {
                return _Elo_NewRating;
            }
            set
            {
                OnElo_NewRatingChanging(value);
                ReportPropertyChanging("Elo_NewRating");
                _Elo_NewRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elo_NewRating");
                OnElo_NewRatingChanged();
            }
        }
        private global::System.Int32 _Elo_NewRating;
        partial void OnElo_NewRatingChanging(global::System.Int32 value);
        partial void OnElo_NewRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_RatingDiff
        {
            get
            {
                return _Tc_RatingDiff;
            }
            set
            {
                OnTc_RatingDiffChanging(value);
                ReportPropertyChanging("Tc_RatingDiff");
                _Tc_RatingDiff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_RatingDiff");
                OnTc_RatingDiffChanged();
            }
        }
        private global::System.Int32 _Tc_RatingDiff;
        partial void OnTc_RatingDiffChanging(global::System.Int32 value);
        partial void OnTc_RatingDiffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Elo_RatingDiff
        {
            get
            {
                return _Elo_RatingDiff;
            }
            set
            {
                OnElo_RatingDiffChanging(value);
                ReportPropertyChanging("Elo_RatingDiff");
                _Elo_RatingDiff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elo_RatingDiff");
                OnElo_RatingDiffChanged();
            }
        }
        private global::System.Int32 _Elo_RatingDiff;
        partial void OnElo_RatingDiffChanging(global::System.Int32 value);
        partial void OnElo_RatingDiffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Elo_NewKFactor
        {
            get
            {
                return _Elo_NewKFactor;
            }
            set
            {
                OnElo_NewKFactorChanging(value);
                ReportPropertyChanging("Elo_NewKFactor");
                _Elo_NewKFactor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Elo_NewKFactor");
                OnElo_NewKFactorChanged();
            }
        }
        private global::System.Int32 _Elo_NewKFactor;
        partial void OnElo_NewKFactorChanging(global::System.Int32 value);
        partial void OnElo_NewKFactorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_OldVolatility
        {
            get
            {
                return _Tc_OldVolatility;
            }
            set
            {
                OnTc_OldVolatilityChanging(value);
                ReportPropertyChanging("Tc_OldVolatility");
                _Tc_OldVolatility = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_OldVolatility");
                OnTc_OldVolatilityChanged();
            }
        }
        private global::System.Int32 _Tc_OldVolatility;
        partial void OnTc_OldVolatilityChanging(global::System.Int32 value);
        partial void OnTc_OldVolatilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tc_VolatilityDiff
        {
            get
            {
                return _Tc_VolatilityDiff;
            }
            set
            {
                OnTc_VolatilityDiffChanging(value);
                ReportPropertyChanging("Tc_VolatilityDiff");
                _Tc_VolatilityDiff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tc_VolatilityDiff");
                OnTc_VolatilityDiffChanged();
            }
        }
        private global::System.Int32 _Tc_VolatilityDiff;
        partial void OnTc_VolatilityDiffChanging(global::System.Int32 value);
        partial void OnTc_VolatilityDiffChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CoderId", "Coders")]
        public Coder Coder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Coder>("Model.FK_CoderId", "Coders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Coder>("Model.FK_CoderId", "Coders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Coder> CoderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Coder>("Model.FK_CoderId", "Coders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Coder>("Model.FK_CoderId", "Coders", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_RoundId", "Rounds")]
        public Round Round
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_RoundId", "Rounds").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_RoundId", "Rounds").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Round> RoundReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Round>("Model.FK_RoundId", "Rounds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Round>("Model.FK_RoundId", "Rounds", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
